Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Deeplay_EnterprisePersonnelAccounting.Models
{
    public enum Sex { Male, Female };
    public class Employee
    {
        [Key]
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public DateTime BirthDate { get; set; }
        public Sex Sex { get; set; }

        public Guid PositionId { get; set; }

        [NotMapped]
        public Position Position { get; set; }

        public Guid SubdivisionId { get; set; }

        [NotMapped]
        public Subdivision Subdivision { get; set; }

        [NotMapped]
        public List<Employee> Subordinates { get; set; }

        public Guid LineManagerId { get; set; }

        [NotMapped]
        public Employee LineManager { get; set; }

        public Employee()
        {
            Id = Guid.NewGuid();
            Name = "";
            Surname = "";
            Patronymic = "";
        }
    }
}

Controllers/EmployeeController.cs
using Deeplay_EnterprisePersonnelAccounting.Data;
using Deeplay_EnterprisePersonnelAccounting.Interfaces;
using Deeplay_EnterprisePersonnelAccounting.Models;
using Deeplay_EnterprisePersonnelAccounting.Services;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Deeplay_EnterprisePersonnelAccounting.Controllers
{
    public class EmployeeController : Controller
    {
        public IEmployeeService employeeService;
        public IPositionService positionService;
        public ISubdivisionService subdivisionService;
        public DBContext db;

        public EmployeeController(DBContext db)
        {
            this.db = db;
            employeeService = new EmployeeService(db);
            positionService = new PositionService(db);
            subdivisionService = new SubdivisionService(db);
        }

        /// <summary>
        /// Fill fields which are not in database
        /// </summary>
        /// <param name="employee"></param>
        private void FillEmplpyeeInfo(Employee employee)
        {
            employee.Subdivision = subdivisionService.GetSubdivisionById(employee.SubdivisionId).Result;
            employee.Position = positionService.GetPositionById(employee.PositionId).Result;
            employee.Subordinates = employeeService.GetSubordinatesById(employee.Id).Result;
        }

        /// <summary>
        /// Searches the database for users by request, by default the request is an empty string
        /// </summary>
        /// <param name="searchRequest"></param>
        /// <returns></returns>
        public IActionResult Search(SearchQuery query)
        {
            query.SubdivisionId = subdivisionService.GetSubdivisionIdByName(query.Subdivision);
            query.PositionId = positionService.GetPositionIdByName(query.Position);

            employeeService.Search(query);
            foreach (var employee in query.Result)
                FillEmplpyeeInfo(employee);

            return View(query);
        }

        /// <summary>
        /// View an employee's profile
        /// </summary>
        /// <returns></returns>
        public IActionResult Employee([FromQuery] string strId)
        {
            var employee = strId == null ? null : employeeService.GetEmployeeById(Guid.Parse(strId)).Result;
            if (employee != null)
                FillEmplpyeeInfo(employee);
            return View(employee);
        }

        /// <summary>
        /// Edit employee's data
        /// </summary>
        /// <returns></returns>
        public IActionResult EditEmployee([FromQuery] string strId = "")
        {
            Employee employee;
            var positions = positionService.GetAllPositions().Result;
            var subdivisions = subdivisionService.GetAllSubdivisions().Result;
            if (strId != "")
            {
                employee = employeeService.GetEmployeeById(Guid.Parse(strId)).Result;
            }
            else
            {
                employee = new Employee();
            }
            return View(new EmployeeEditModel()
            {
                Employee = employee,
                Positions = positions,
                Subdivisions = subdivisions
            });
        }

        /// <summary>
        /// Add new employee or update
        /// </summary>
        /// <returns></returns>
        public IActionResult AddOrUpdateEmployee(Employee employee)
        {
            employeeService.AddOrUpdateEmployee(employee);
            return Redirect("/Employee/Employee?strId=" + employee.Id.ToString());
        }

        /// <summary>
        /// Remove employee
        /// </summary>
        /// <returns></returns>
        public IActionResult DeleteEmployee([FromQuery] string strId)
        {
            employeeService.DeleteEmployee(Guid.Parse(strId));
            return Redirect("/");
        }

        /// <summary>
        /// Helps to search appropriate candidates in ajax search form by partial input
        /// </summary>
        /// <param name="queryStr"></param>
        /// <returns></returns>
        public IActionResult SearchEmployeeByRequisites([FromQuery] string queryStr)
        {
            var employees = employeeService.Search(queryStr);
            return View(employees);
        }
    }
}

Controllers/PositionController.cs
using Deeplay_EnterprisePersonnelAccounting.Data;
using Deeplay_EnterprisePersonnelAccounting.Interfaces;
using Deeplay_EnterprisePersonnelAccounting.Models;
using Deeplay_EnterprisePersonnelAccounting.Services;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Deeplay_EnterprisePersonnelAccounting.Controllers
{
    public class PositionController : Controller
    {
        public DBContext db { get; set; }
        public IPositionService positionService;

        public PositionController(DBContext db)
        {
            this.db = db;
            positionService = new PositionService(db);
        }

        /// <summary>
        /// Show all positions
        /// </summary>
        /// <returns></returns>
        public IActionResult ListPositions()
        {
            var positions = positionService.GetAllPositions().Result;
            return View(positions);
        }

        /// <summary>
        /// Edit position's name
        /// </summary>
        /// <param name="strId"></param>
        /// <returns></returns>
        public IActionResult EditPosition([FromQuery] string strId = "")
        {
            Position position;
            if (strId != "")
            {
                var Id = Guid.Parse(strId);
                position = positionService.GetPositionById(Id).Result;
            }
            else
            {
                position = new Position();
            }
            return View(position);
        }

        /// <summary>
        /// Remove position
        /// </summary>
        /// <param name="strId"></param>
        /// <returns></returns>
        public IActionResult DeletePosition([FromQuery] string strId)
        {
            if (strId != null)
                positionService.DeletePosition(Guid.Parse(strId));
            return Redirect("/Position/ListPositions");
        }

        /// <summary>
        /// Add or update position
        /// </summary>
        /// <param name="position"></param>
        /// <returns></returns>
        public IActionResult AddOrUpdatePosition(Position position)
        {
            positionService.AddOrUpdatePosition(position);
            return Redirect("/Position/ListPositions");
        }
    }
}

Controllers/SubdivisionController.cs
using Deeplay_EnterprisePersonnelAccounting.Data;
using Deeplay_EnterprisePersonnelAccounting.Interfaces;
using Deeplay_EnterprisePersonnelAccounting.Models;
using Deeplay_EnterprisePersonnelAccounting.Services;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Deeplay_EnterprisePersonnelAccounting.Controllers
{
    public class SubdivisionController : Controller
    {
        public DBContext db { get; set; }
        public ISubdivisionService subdivisionService;

        public SubdivisionController(DBContext db)
        {
            this.db = db;
            subdivisionService = new SubdivisionService(db);
        }

        /// <summary>
        /// Show all subdivisions
        /// </summary>
        /// <returns></returns>
        public IActionResult ListSubdivisions()
        {
            var subdivisions = subdivisionService.GetAllSubdivisions().Result;
            return View(subdivisions);
        }

        /// <summary>
        /// Edit subdivision's Name
        /// </summary>
        /// <param name="strId"></param>
        /// <returns></returns>
        public IActionResult EditSubdivision([FromQuery] string strId = "")
        {
            Subdivision subdivision;
            if (strId != "")
            {
                var Id = Guid.Parse(strId);
                subdivision = subdivisionService.GetSubdivisionById(Id).Result;
            }
            else
            {
                subdivision = new Subdivision();
            }
            return View(subdivision);
        }

        /// <summary>
        /// Remove subdivision
        /// </summary>
        /// <param name="strId"></param>
        /// <returns></returns>
        public IActionResult DeleteSubdivision([FromQuery] string strId)
        {
            if (strId != null)
                subdivisionService.DeleteSubdivision(Guid.Parse(strId));
            return Redirect("/Subdivision/ListSubdivisions");
        }

        /// <summary>
        /// Add or update subdivision
        /// </summary>
        /// <param name="subdivision"></param>
        /// <returns></returns>
        public IActionResult AddOrUpdateSubdivision(Subdivision subdivision)
        {
            subdivisionService.AddOrUpdateSubdivision(subdivision);
            return Redirect("/Subdivision/ListSubdivisions");
        }
    }
}

Views/Employee/EditEmployee.cshtml
@model Deeplay_EnterprisePersonnelAccounting.Models.EmployeeEditModel
@{
    var now = DateTime.Now.ToString("yyyy'-'MM'-'dd");
    var now_18 = DateTime.Now.AddYears(-18).ToString("yyyy'-'MM'-'dd");
    var now_100 = DateTime.Now.AddYears(-100).ToString("yyyy'-'MM'-'dd");
    var birthDateModel = Model.Employee.BirthDate.ToString("yyyy'-'MM'-'dd");
    var birthDateValue = birthDateModel != "0001-01-01" ? birthDateModel : now_18;
    var positions = Model.Positions;
    var subdivisions = Model.Subdivisions;
    var managerFullName = Model.Employee.LineManager != null ? Model.Employee.LineManager.Surname + " " + Model.Employee.LineManager.Name + " " + Model.Employee.LineManager.Patronymic : "";
    var nullGuid = new Guid();
}

<h2>Edit employee</h2>
<form asp-controller="Employee" asp-action="AddOrUpdateEmployee" method="get">
    <input asp-for="Employee.Id" readonly hidden/>
    <ul>
        <li><input type="text" placeholder="Enter employee surname" value="@Model.Employee.Surname" name="Employee.Surname"></li>
        <li><input type="text" placeholder="Enter employee name" value="@Model.Employee.Name" name="Employee.Name"></li>
        <li><input type="text" placeholder="Enter employee patronymic" value="@Model.Employee.Patronymic" name="Employee.Patronymic"></li>
        <li><input type="date" placeholder="@now_18" min="@now_100" max="@now_18" name="Employee.BirthDate" value="@birthDateValue"></li>
        <li>
            @{
                var maleChecked = (Model.Employee.Sex == Sex.Male) ? "checked" : "";   
                var femaleChecked = (Model.Employee.Sex == Sex.Female) ? "checked" : "";   
            }
            <input type="radio" name="Employee.Sex" value="Male" id="Male" @maleChecked><label for="Male">Male</label><br></input>
            <input type="radio" name="Employee.Sex" value="Female" id="Female" @femaleChecked><label for="Female">Female</label><br></input>
        </li>
        <li>
            <select name="Employee.PositionId">
                <option value="@nullGuid" selected>---</option>
                @foreach(var p in positions)
                {
                    @if(p.Id == Model.Employee.PositionId)
                    {
                        <option value="@p.Id" selected>@p.PositionName</option>
                    }
                    else
                    {
                        <option value="@p.Id">@p.PositionName</option>
                    }
                }
            </select>
        </li>
        <li>
            <select name="Employee.SubdivisionId">
                <option value="@nullGuid" selected>---</option>
                @foreach(var s in subdivisions)
                {
                    @if(s.Id == Model.Employee.SubdivisionId)
                    {
                        <option value="@s.Id" selected>@s.SubdivisionName</option>
                    }
                    else
                    {
                        <option value="@s.Id">@s.SubdivisionName</option>
                    }
                }
            </select>
        </li>
        <li><input type="text" placeholder="[Surname Name Patronymic]" value="@managerFullName" id="managerName" onkeyup="updateManagerList()" onchange="updateManagerId()" list="Managers"></li>
        <input type="hidden" value="" name="Employee.LineManagerId" id="managerId" />
        <datalist id="Managers">
        </datalist>
        <script>
            var managerNameToId = {};

            function updateManagerId() {
                var id = managerNameToId[document.getElementById("managerName").value];
                document.getElementById("managerId").value = id == undefined ? '' : id;
            }

            function updateManagerList() {
                var value = document.getElementById("managerName").value;
                if (value != '')
                {
                    var req = new XMLHttpRequest();
                    req.open('GET', '/Employee/SearchEmployeeByRequisites/?queryStr=' + value);
                    req.send();
                    req.onload = function() {
                        if (req.status != 200)
                            console.log(`Error ${req.status}: ${req.statusText}`);
                        else
                            processResponse(req.response);
                    };
                    req.onerror = function() { console.log("Error"); };
                }
            }

            function processResponse(response) {
                var parser = new DOMParser();
                var xmlDoc = parser.parseFromString(response, "text/xml");
                var empl = xmlDoc.getElementsByTagName("Employee");
                var managersList = document.getElementById("Managers");
                managersList.textContent = '';
                managerNameToId = {};
                for (var i = 0; i < empl.length; ++i) {
                    var e = empl[i];
                    var name = e.getElementsByTagName("FullName")[0].textContent;
                    var id = e.getElementsByTagName("Id")[0].textContent
                    managerNameToId[name] = id;

                    var option = document.createElement('option');
                    option.setAttribute('value', name);
                    managersList.appendChild(option);
                }
                updateManagerId();
            }
        </script>
    </ul>
    <button type="submit">Save</button><a href="/" class="btn">Cancel</a>
</form>

Views/Employee/Employee.cshtml
@model Deeplay_EnterprisePersonnelAccounting.Models.Employee

@if (Model == null)
{
    <h2>No such employee</h2>
}
else
{
    <div class="block">
        <a href="/"><button>Back</button></a>
        <a asp-controller="Employee" asp-action="EditEmployee" asp-route-strId="@Model.Id"><button>Edit</button></a>
        <a asp-controller="Employee" asp-action="DeleteEmployee" asp-route-strId="@Model.Id" onclick="return confirm('Confirm?')"><button>Delete</button></a>
    </div>
    <div class="block">
        <h2>Employee</h2>
        <ul>
            <li><span class="caption">Name:</span> @Model.Surname @Model.Name @Model.Patronymic</li>
            <li><span class="caption">Birth date:</span> @Model.BirthDate.ToString("yyyy.MM.dd")</li>
            <li><span class="caption">Sex:</span> @Model.Sex.ToString()</li>
            @if (Model.Position != null)
            {
                <li><span class="caption">Position:</span> @Model.Position.PositionName</li>
            }
            @if (Model.Subdivision != null)
            {
                <li><span class="caption">Subdivision:</span> @Model.Subdivision.SubdivisionName</li>
            }
            @if (Model.LineManager != null)
            {
                <li><span class="caption">Manager:</span> @Model.LineManager.Surname @Model.LineManager.Name @Model.LineManager.Patronymic</li>
            }
            @if (Model.Subordinates != null && Model.Subordinates.Count != 0)
            {
                <li><span class="caption">Subordinates:</span>
                <ul class="list">
                @foreach(var sub in Model.Subordinates)
                {
                    <a asp-controller="Employee" asp-action="Employee" asp-route-strId="@sub.Id">
                    <li>@sub.Surname @sub.Name @sub.Patronymic</li>
                    </a>
                }
                </ul>
                </li>
            }
        </ul>
    </div>
}

Views/Employee/Search.cshtml
@using System.Text;
@{
    bool IsValid(SearchQuery query)
    {
        return true;
    };
}
@model Deeplay_EnterprisePersonnelAccounting.Models.SearchQuery

<div class="block" id="actions">
    <h2>Actions</h2>
    <a asp-controller="Employee" asp-action="EditEmployee" class="btn">Add employee</a>
    <a asp-controller="Position" asp-action="ListPositions" class="btn">List and edit positions</a>
    <a asp-controller="Subdivision" asp-action="ListSubdivisions" class="btn">List and edit subdivisions</a>
</div>

<div class="block" id="newSearch">
    <h2>New search</h2>
    <form asp-controller="Employee" asp-action="Search" method="get">
        <ul>
            <li><input type="text" placeholder="Enter employee surname" name="query.Surname"></li>
            <li><input type="text" placeholder="Enter employee name" name="query.Name"></li>
            <li><input type="text" placeholder="Enter employee patronymic" name="query.Patronymic"></li>
            <li><input type="text" placeholder="Enter employee position" name="query.Position"></li>
            <li><input type="text" placeholder="Enter employee subdivision" name="query.Subdivision"></li>
            <li><button type="submit">Search</button></li>
        </ul>
    </form>
</div>

<div class="block" id="searchResults">
@if(IsValid(Model))
{
    @if (Model.Result.Count == 0)
    {
        <h2>Not found</h2>
    }
    else
    {
        <h2>Search result</h2>
        <span><em>@Model.Result.Count of @Model.ResultCount</em></span>
        <ul>
            @foreach (var res in Model.Result)
            {
                <a asp-controller="Employee" asp-action="Employee" asp-route-strId="@res.Id">
                    <li>
                        <span>@res.Surname @res.Name @res.Patronymic</span>
                        @if (res.Position != null)
                        {
                            <span>| position: @res.Position.PositionName</span>
                        }
                        @if (res.Subdivision != null)
                        {
                            <span>| subdivision: @res.Subdivision.SubdivisionName</span>
                        }
                    </li>
                </a>
            }
        </ul>
        @if (Model.ResultCount > Model.ResultsPerPage)
        {
            <span>Pages:</span>
            @for (var i = 0; i < (Model.ResultCount + Model.ResultsPerPage - 1) / Model.ResultsPerPage; ++i)
            {
                var i1 = i + 1;
                if (i == Model.Page)
                {
                    @i1
                }
                else
                {
                    <a asp-controller="Employee" asp-action="Search"
                    asp-route-query.Surname="@Model.Surname"
                    asp-route-query.Name="@Model.Name"
                    asp-route-query.Patronymic="@Model.Patronymic"
                    asp-route-query.Position="@Model.Position"
                    asp-route-query.Subdivision="@Model.Subdivision"
                    asp-route-query.Page="@i"
                    >@i1</a>
                }
            }
        }
    }
}
else
{
    <p>Invalid request. Try to enter name, surname, patronimic, position or subdivision.</p>
}
</div>

Views/Employee/SearchEmployeeByRequisites.cshtml
@{
    Layout = null;
}
@model IEnumerable<Employee>
<?xml version="1.0"?>
<List>
    @foreach(var empl in Model)
    {
        <Employee>
            <FullName>@empl.Surname @empl.Name @empl.Patronymic</FullName>
            <Id>@empl.Id</Id>
        </Employee>
    }
</List>